// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agents.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (agent_id, name, prefix, key_hash, scopes, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, agent_id, name, prefix, key_hash, scopes, expires_at, last_used_at, revoked_at, created_at
`

type CreateAPIKeyParams struct {
	AgentID   uuid.UUID          `json:"agent_id"`
	Name      string             `json:"name"`
	Prefix    string             `json:"prefix"`
	KeyHash   string             `json:"key_hash"`
	Scopes    []string           `json:"scopes"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.AgentID,
		arg.Name,
		arg.Prefix,
		arg.KeyHash,
		arg.Scopes,
		arg.ExpiresAt,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Name,
		&i.Prefix,
		&i.KeyHash,
		&i.Scopes,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createAgent = `-- name: CreateAgent :one
INSERT INTO agents (name, developer_id, organization_id, description)
VALUES ($1, $2, $3, $4)
RETURNING id, name, developer_id, organization_id, description, active, last_seen_at, created_at, updated_at
`

type CreateAgentParams struct {
	Name           string     `json:"name"`
	DeveloperID    *uuid.UUID `json:"developer_id"`
	OrganizationID *uuid.UUID `json:"organization_id"`
	Description    *string    `json:"description"`
}

func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error) {
	row := q.db.QueryRow(ctx, createAgent,
		arg.Name,
		arg.DeveloperID,
		arg.OrganizationID,
		arg.Description,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DeveloperID,
		&i.OrganizationID,
		&i.Description,
		&i.Active,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT id, agent_id, name, prefix, key_hash, scopes, expires_at, last_used_at, revoked_at, created_at FROM api_keys
WHERE key_hash = $1
  AND revoked_at IS NULL
  AND (expires_at IS NULL OR expires_at > now())
`

func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByHash, keyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Name,
		&i.Prefix,
		&i.KeyHash,
		&i.Scopes,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAgent = `-- name: GetAgent :one
SELECT id, name, developer_id, organization_id, description, active, last_seen_at, created_at, updated_at FROM agents WHERE id = $1
`

func (q *Queries) GetAgent(ctx context.Context, id uuid.UUID) (Agent, error) {
	row := q.db.QueryRow(ctx, getAgent, id)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DeveloperID,
		&i.OrganizationID,
		&i.Description,
		&i.Active,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAPIKeysByAgent = `-- name: ListAPIKeysByAgent :many
SELECT id, agent_id, name, prefix, key_hash, scopes, expires_at, last_used_at, revoked_at, created_at FROM api_keys
WHERE agent_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListAPIKeysByAgent(ctx context.Context, agentID uuid.UUID) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeysByAgent, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.Name,
			&i.Prefix,
			&i.KeyHash,
			&i.Scopes,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentsByOrganization = `-- name: ListAgentsByOrganization :many
SELECT id, name, developer_id, organization_id, description, active, last_seen_at, created_at, updated_at FROM agents
WHERE organization_id = $1
ORDER BY name
`

func (q *Queries) ListAgentsByOrganization(ctx context.Context, organizationID *uuid.UUID) ([]Agent, error) {
	rows, err := q.db.Query(ctx, listAgentsByOrganization, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Agent{}
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DeveloperID,
			&i.OrganizationID,
			&i.Description,
			&i.Active,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :one
UPDATE api_keys
SET revoked_at = now()
WHERE id = $1 AND revoked_at IS NULL
RETURNING id, agent_id, name, prefix, key_hash, scopes, expires_at, last_used_at, revoked_at, created_at
`

func (q *Queries) RevokeAPIKey(ctx context.Context, id uuid.UUID) (ApiKey, error) {
	row := q.db.QueryRow(ctx, revokeAPIKey, id)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Name,
		&i.Prefix,
		&i.KeyHash,
		&i.Scopes,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const touchAPIKeyLastUsed = `-- name: TouchAPIKeyLastUsed :exec
UPDATE api_keys SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchAPIKeyLastUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchAPIKeyLastUsed, id)
	return err
}

const touchAgentLastSeen = `-- name: TouchAgentLastSeen :exec
UPDATE agents SET last_seen_at = now(), updated_at = now() WHERE id = $1
`

func (q *Queries) TouchAgentLastSeen(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchAgentLastSeen, id)
	return err
}

const updateAgent = `-- name: UpdateAgent :one
UPDATE agents
SET
    name = COALESCE($2, name),
    description = COALESCE($3, description),
    active = COALESCE($4, active),
    updated_at = now()
WHERE id = $1
RETURNING id, name, developer_id, organization_id, description, active, last_seen_at, created_at, updated_at
`

type UpdateAgentParams struct {
	ID          uuid.UUID `json:"id"`
	Name        *string   `json:"name"`
	Description *string   `json:"description"`
	Active      *bool     `json:"active"`
}

func (q *Queries) UpdateAgent(ctx context.Context, arg UpdateAgentParams) (Agent, error) {
	row := q.db.QueryRow(ctx, updateAgent,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Active,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DeveloperID,
		&i.OrganizationID,
		&i.Description,
		&i.Active,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
