// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: comments_activities.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createActivity = `-- name: CreateActivity :one
INSERT INTO task_activities (task_id, actor_type, actor_id, action, old_value, new_value, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, task_id, actor_type, actor_id, action, old_value, new_value, metadata, created_at
`

type CreateActivityParams struct {
	TaskID    uuid.UUID  `json:"task_id"`
	ActorType string     `json:"actor_type"`
	ActorID   *uuid.UUID `json:"actor_id"`
	Action    string     `json:"action"`
	OldValue  []byte     `json:"old_value"`
	NewValue  []byte     `json:"new_value"`
	Metadata  []byte     `json:"metadata"`
}

func (q *Queries) CreateActivity(ctx context.Context, arg CreateActivityParams) (TaskActivity, error) {
	row := q.db.QueryRow(ctx, createActivity,
		arg.TaskID,
		arg.ActorType,
		arg.ActorID,
		arg.Action,
		arg.OldValue,
		arg.NewValue,
		arg.Metadata,
	)
	var i TaskActivity
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.ActorType,
		&i.ActorID,
		&i.Action,
		&i.OldValue,
		&i.NewValue,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const createComment = `-- name: CreateComment :one
INSERT INTO task_comments (task_id, author_type, author_id, content, metadata)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, task_id, author_type, author_id, content, metadata, created_at, updated_at
`

type CreateCommentParams struct {
	TaskID     uuid.UUID  `json:"task_id"`
	AuthorType string     `json:"author_type"`
	AuthorID   *uuid.UUID `json:"author_id"`
	Content    string     `json:"content"`
	Metadata   []byte     `json:"metadata"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (TaskComment, error) {
	row := q.db.QueryRow(ctx, createComment,
		arg.TaskID,
		arg.AuthorType,
		arg.AuthorID,
		arg.Content,
		arg.Metadata,
	)
	var i TaskComment
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.AuthorType,
		&i.AuthorID,
		&i.Content,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActivitiesByTask = `-- name: ListActivitiesByTask :many
SELECT id, task_id, actor_type, actor_id, action, old_value, new_value, metadata, created_at FROM task_activities
WHERE task_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListActivitiesByTask(ctx context.Context, taskID uuid.UUID) ([]TaskActivity, error) {
	rows, err := q.db.Query(ctx, listActivitiesByTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskActivity{}
	for rows.Next() {
		var i TaskActivity
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.ActorType,
			&i.ActorID,
			&i.Action,
			&i.OldValue,
			&i.NewValue,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommentsByTask = `-- name: ListCommentsByTask :many
SELECT id, task_id, author_type, author_id, content, metadata, created_at, updated_at FROM task_comments
WHERE task_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListCommentsByTask(ctx context.Context, taskID uuid.UUID) ([]TaskComment, error) {
	rows, err := q.db.Query(ctx, listCommentsByTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskComment{}
	for rows.Next() {
		var i TaskComment
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.AuthorType,
			&i.AuthorID,
			&i.Content,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
