// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organizations.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const acceptInvite = `-- name: AcceptInvite :one
UPDATE organization_invites
SET accepted_at = now()
WHERE id = $1
  AND accepted_at IS NULL
RETURNING id, organization_id, email, role, token_hash, created_by, expires_at, accepted_at, created_at
`

func (q *Queries) AcceptInvite(ctx context.Context, id uuid.UUID) (OrganizationInvite, error) {
	row := q.db.QueryRow(ctx, acceptInvite, id)
	var i OrganizationInvite
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const addOrganizationMember = `-- name: AddOrganizationMember :one
INSERT INTO organization_members (organization_id, user_id, role)
VALUES ($1, $2, $3)
RETURNING organization_id, user_id, role, created_at
`

type AddOrganizationMemberParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	UserID         uuid.UUID `json:"user_id"`
	Role           string    `json:"role"`
}

func (q *Queries) AddOrganizationMember(ctx context.Context, arg AddOrganizationMemberParams) (OrganizationMember, error) {
	row := q.db.QueryRow(ctx, addOrganizationMember, arg.OrganizationID, arg.UserID, arg.Role)
	var i OrganizationMember
	err := row.Scan(
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const countAdminMembershipsForUser = `-- name: CountAdminMembershipsForUser :one
SELECT count(*)::bigint
FROM organization_members
WHERE user_id = $1 AND role = 'admin'
`

func (q *Queries) CountAdminMembershipsForUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAdminMembershipsForUser, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countMembershipsForUser = `-- name: CountMembershipsForUser :one
SELECT count(*)::bigint FROM organization_members WHERE user_id = $1
`

func (q *Queries) CountMembershipsForUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countMembershipsForUser, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (name, slug, color)
VALUES ($1, $2, $3)
RETURNING id, name, slug, color, active, created_at, updated_at
`

type CreateOrganizationParams struct {
	Name  string  `json:"name"`
	Slug  string  `json:"slug"`
	Color *string `json:"color"`
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization, arg.Name, arg.Slug, arg.Color)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Color,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrganizationInvite = `-- name: CreateOrganizationInvite :one
INSERT INTO organization_invites (organization_id, email, role, token_hash, created_by, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, organization_id, email, role, token_hash, created_by, expires_at, accepted_at, created_at
`

type CreateOrganizationInviteParams struct {
	OrganizationID uuid.UUID          `json:"organization_id"`
	Email          *string            `json:"email"`
	Role           string             `json:"role"`
	TokenHash      string             `json:"token_hash"`
	CreatedBy      uuid.UUID          `json:"created_by"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateOrganizationInvite(ctx context.Context, arg CreateOrganizationInviteParams) (OrganizationInvite, error) {
	row := q.db.QueryRow(ctx, createOrganizationInvite,
		arg.OrganizationID,
		arg.Email,
		arg.Role,
		arg.TokenHash,
		arg.CreatedBy,
		arg.ExpiresAt,
	)
	var i OrganizationInvite
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteInvite = `-- name: DeleteInvite :exec
DELETE FROM organization_invites
WHERE id = $1 AND organization_id = $2 AND accepted_at IS NULL
`

type DeleteInviteParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) DeleteInvite(ctx context.Context, arg DeleteInviteParams) error {
	_, err := q.db.Exec(ctx, deleteInvite, arg.ID, arg.OrganizationID)
	return err
}

const getOrganization = `-- name: GetOrganization :one
SELECT id, name, slug, color, active, created_at, updated_at FROM organizations WHERE id = $1
`

func (q *Queries) GetOrganization(ctx context.Context, id uuid.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganization, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Color,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationBySlug = `-- name: GetOrganizationBySlug :one
SELECT id, name, slug, color, active, created_at, updated_at FROM organizations WHERE slug = $1
`

func (q *Queries) GetOrganizationBySlug(ctx context.Context, slug string) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationBySlug, slug)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Color,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationMember = `-- name: GetOrganizationMember :one
SELECT organization_id, user_id, role, created_at FROM organization_members
WHERE organization_id = $1 AND user_id = $2
`

type GetOrganizationMemberParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	UserID         uuid.UUID `json:"user_id"`
}

func (q *Queries) GetOrganizationMember(ctx context.Context, arg GetOrganizationMemberParams) (OrganizationMember, error) {
	row := q.db.QueryRow(ctx, getOrganizationMember, arg.OrganizationID, arg.UserID)
	var i OrganizationMember
	err := row.Scan(
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getPendingInviteByTokenHash = `-- name: GetPendingInviteByTokenHash :one
SELECT
    i.id,
    i.organization_id,
    i.email,
    i.role,
    i.token_hash,
    i.created_by,
    i.expires_at,
    i.accepted_at,
    i.created_at,
    o.name AS organization_name
FROM organization_invites i
JOIN organizations o ON o.id = i.organization_id
WHERE i.token_hash = $1
  AND i.accepted_at IS NULL
  AND i.expires_at > now()
`

type GetPendingInviteByTokenHashRow struct {
	ID               uuid.UUID          `json:"id"`
	OrganizationID   uuid.UUID          `json:"organization_id"`
	Email            *string            `json:"email"`
	Role             string             `json:"role"`
	TokenHash        string             `json:"token_hash"`
	CreatedBy        uuid.UUID          `json:"created_by"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	AcceptedAt       pgtype.Timestamptz `json:"accepted_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	OrganizationName string             `json:"organization_name"`
}

func (q *Queries) GetPendingInviteByTokenHash(ctx context.Context, tokenHash string) (GetPendingInviteByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getPendingInviteByTokenHash, tokenHash)
	var i GetPendingInviteByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
		&i.OrganizationName,
	)
	return i, err
}

const listOrganizationMembers = `-- name: ListOrganizationMembers :many
SELECT
    m.organization_id,
    m.user_id,
    m.role,
    m.created_at,
    u.name AS user_name,
    u.email AS user_email,
    u.avatar_url AS user_avatar_url,
    u.active AS user_active
FROM organization_members m
JOIN users u ON u.id = m.user_id
WHERE m.organization_id = $1
ORDER BY u.name
`

type ListOrganizationMembersRow struct {
	OrganizationID uuid.UUID          `json:"organization_id"`
	UserID         uuid.UUID          `json:"user_id"`
	Role           string             `json:"role"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UserName       string             `json:"user_name"`
	UserEmail      string             `json:"user_email"`
	UserAvatarUrl  *string            `json:"user_avatar_url"`
	UserActive     bool               `json:"user_active"`
}

func (q *Queries) ListOrganizationMembers(ctx context.Context, organizationID uuid.UUID) ([]ListOrganizationMembersRow, error) {
	rows, err := q.db.Query(ctx, listOrganizationMembers, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrganizationMembersRow{}
	for rows.Next() {
		var i ListOrganizationMembersRow
		if err := rows.Scan(
			&i.OrganizationID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.UserName,
			&i.UserEmail,
			&i.UserAvatarUrl,
			&i.UserActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizationsForUser = `-- name: ListOrganizationsForUser :many
SELECT o.id, o.name, o.slug, o.color, o.active, o.created_at, o.updated_at
FROM organizations o
JOIN organization_members m ON m.organization_id = o.id
WHERE m.user_id = $1
  AND o.active = TRUE
ORDER BY o.name
`

func (q *Queries) ListOrganizationsForUser(ctx context.Context, userID uuid.UUID) ([]Organization, error) {
	rows, err := q.db.Query(ctx, listOrganizationsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Organization{}
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Color,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingInvites = `-- name: ListPendingInvites :many
SELECT id, organization_id, email, role, token_hash, created_by, expires_at, accepted_at, created_at
FROM organization_invites
WHERE organization_id = $1
  AND accepted_at IS NULL
  AND expires_at > now()
ORDER BY created_at DESC
`

func (q *Queries) ListPendingInvites(ctx context.Context, organizationID uuid.UUID) ([]OrganizationInvite, error) {
	rows, err := q.db.Query(ctx, listPendingInvites, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrganizationInvite{}
	for rows.Next() {
		var i OrganizationInvite
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Email,
			&i.Role,
			&i.TokenHash,
			&i.CreatedBy,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeOrganizationMember = `-- name: RemoveOrganizationMember :exec
DELETE FROM organization_members
WHERE organization_id = $1 AND user_id = $2
`

type RemoveOrganizationMemberParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	UserID         uuid.UUID `json:"user_id"`
}

func (q *Queries) RemoveOrganizationMember(ctx context.Context, arg RemoveOrganizationMemberParams) error {
	_, err := q.db.Exec(ctx, removeOrganizationMember, arg.OrganizationID, arg.UserID)
	return err
}

const updateOrganization = `-- name: UpdateOrganization :one
UPDATE organizations
SET
    name = COALESCE($2, name),
    color = COALESCE($3, color),
    updated_at = now()
WHERE id = $1
RETURNING id, name, slug, color, active, created_at, updated_at
`

type UpdateOrganizationParams struct {
	ID    uuid.UUID `json:"id"`
	Name  *string   `json:"name"`
	Color *string   `json:"color"`
}

func (q *Queries) UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, updateOrganization, arg.ID, arg.Name, arg.Color)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Color,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrganizationMemberRole = `-- name: UpdateOrganizationMemberRole :one
UPDATE organization_members
SET role = $3
WHERE organization_id = $1 AND user_id = $2
RETURNING organization_id, user_id, role, created_at
`

type UpdateOrganizationMemberRoleParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	UserID         uuid.UUID `json:"user_id"`
	Role           string    `json:"role"`
}

func (q *Queries) UpdateOrganizationMemberRole(ctx context.Context, arg UpdateOrganizationMemberRoleParams) (OrganizationMember, error) {
	row := q.db.QueryRow(ctx, updateOrganizationMemberRole, arg.OrganizationID, arg.UserID, arg.Role)
	var i OrganizationMember
	err := row.Scan(
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}
