// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: projects.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (organization_id, name, key, description)
VALUES ($1, $2, $3, $4)
RETURNING id, organization_id, name, key, description, task_counter, active, created_at, updated_at
`

type CreateProjectParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Name           string    `json:"name"`
	Key            string    `json:"key"`
	Description    string    `json:"description"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.OrganizationID,
		arg.Name,
		arg.Key,
		arg.Description,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Key,
		&i.Description,
		&i.TaskCounter,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProject = `-- name: GetProject :one
SELECT id, organization_id, name, key, description, task_counter, active, created_at, updated_at FROM projects WHERE id = $1
`

func (q *Queries) GetProject(ctx context.Context, id uuid.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Key,
		&i.Description,
		&i.TaskCounter,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectByOrgAndKey = `-- name: GetProjectByOrgAndKey :one
SELECT id, organization_id, name, key, description, task_counter, active, created_at, updated_at FROM projects
WHERE organization_id = $1 AND key = $2
`

type GetProjectByOrgAndKeyParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Key            string    `json:"key"`
}

func (q *Queries) GetProjectByOrgAndKey(ctx context.Context, arg GetProjectByOrgAndKeyParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByOrgAndKey, arg.OrganizationID, arg.Key)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Key,
		&i.Description,
		&i.TaskCounter,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementProjectTaskCounter = `-- name: IncrementProjectTaskCounter :one
UPDATE projects
SET task_counter = task_counter + 1, updated_at = now()
WHERE id = $1
RETURNING task_counter
`

func (q *Queries) IncrementProjectTaskCounter(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, incrementProjectTaskCounter, id)
	var task_counter int32
	err := row.Scan(&task_counter)
	return task_counter, err
}

const listProjectsByOrganization = `-- name: ListProjectsByOrganization :many
SELECT id, organization_id, name, key, description, task_counter, active, created_at, updated_at FROM projects
WHERE organization_id = $1
  AND active = TRUE
ORDER BY name
`

func (q *Queries) ListProjectsByOrganization(ctx context.Context, organizationID uuid.UUID) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsByOrganization, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Key,
			&i.Description,
			&i.TaskCounter,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET
    name = COALESCE($2, name),
    description = COALESCE($3, description),
    updated_at = now()
WHERE id = $1
RETURNING id, organization_id, name, key, description, task_counter, active, created_at, updated_at
`

type UpdateProjectParams struct {
	ID          uuid.UUID `json:"id"`
	Name        *string   `json:"name"`
	Description *string   `json:"description"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject, arg.ID, arg.Name, arg.Description)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Key,
		&i.Description,
		&i.TaskCounter,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
