// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: tasks.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const archiveTask = `-- name: ArchiveTask :one
UPDATE tasks
SET
    archived_at = now(),
    version = version + 1,
    updated_at = now()
WHERE id = $1
  AND version = $2
  AND archived_at IS NULL
RETURNING id, number, organization_id, project_id, title, description, acceptance_criteria, status, priority, assignee_id, reporter_id, due_date, position, blocked, blocked_reason, source, external_ref, source_metadata, completion_summary, version, archived_at, created_at, updated_at
`

type ArchiveTaskParams struct {
	ID      uuid.UUID `json:"id"`
	Version int32     `json:"version"`
}

func (q *Queries) ArchiveTask(ctx context.Context, arg ArchiveTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, archiveTask, arg.ID, arg.Version)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.OrganizationID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.AcceptanceCriteria,
		&i.Status,
		&i.Priority,
		&i.AssigneeID,
		&i.ReporterID,
		&i.DueDate,
		&i.Position,
		&i.Blocked,
		&i.BlockedReason,
		&i.Source,
		&i.ExternalRef,
		&i.SourceMetadata,
		&i.CompletionSummary,
		&i.Version,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const clearTaskAssignee = `-- name: ClearTaskAssignee :one
UPDATE tasks
SET
    assignee_id = NULL,
    version = version + 1,
    updated_at = now()
WHERE id = $1
  AND version = $2
  AND archived_at IS NULL
RETURNING id, number, organization_id, project_id, title, description, acceptance_criteria, status, priority, assignee_id, reporter_id, due_date, position, blocked, blocked_reason, source, external_ref, source_metadata, completion_summary, version, archived_at, created_at, updated_at
`

type ClearTaskAssigneeParams struct {
	ID              uuid.UUID `json:"id"`
	ExpectedVersion int32     `json:"expected_version"`
}

func (q *Queries) ClearTaskAssignee(ctx context.Context, arg ClearTaskAssigneeParams) (Task, error) {
	row := q.db.QueryRow(ctx, clearTaskAssignee, arg.ID, arg.ExpectedVersion)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.OrganizationID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.AcceptanceCriteria,
		&i.Status,
		&i.Priority,
		&i.AssigneeID,
		&i.ReporterID,
		&i.DueDate,
		&i.Position,
		&i.Blocked,
		&i.BlockedReason,
		&i.Source,
		&i.ExternalRef,
		&i.SourceMetadata,
		&i.CompletionSummary,
		&i.Version,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countTaskComments = `-- name: CountTaskComments :many
SELECT task_id, count(*)::int AS comment_count
FROM task_comments
WHERE task_id = ANY($1::uuid[])
GROUP BY task_id
`

type CountTaskCommentsRow struct {
	TaskID       uuid.UUID `json:"task_id"`
	CommentCount int32     `json:"comment_count"`
}

func (q *Queries) CountTaskComments(ctx context.Context, taskIds []uuid.UUID) ([]CountTaskCommentsRow, error) {
	rows, err := q.db.Query(ctx, countTaskComments, taskIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountTaskCommentsRow{}
	for rows.Next() {
		var i CountTaskCommentsRow
		if err := rows.Scan(&i.TaskID, &i.CommentCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (
    number,
    organization_id,
    project_id,
    title,
    description,
    acceptance_criteria,
    status,
    priority,
    assignee_id,
    reporter_id,
    due_date,
    position,
    blocked,
    blocked_reason,
    source,
    external_ref,
    source_metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17
)
RETURNING id, number, organization_id, project_id, title, description, acceptance_criteria, status, priority, assignee_id, reporter_id, due_date, position, blocked, blocked_reason, source, external_ref, source_metadata, completion_summary, version, archived_at, created_at, updated_at
`

type CreateTaskParams struct {
	Number             int32           `json:"number"`
	OrganizationID     uuid.UUID       `json:"organization_id"`
	ProjectID          uuid.UUID       `json:"project_id"`
	Title              string          `json:"title"`
	Description        string          `json:"description"`
	AcceptanceCriteria string          `json:"acceptance_criteria"`
	Status             string          `json:"status"`
	Priority           string          `json:"priority"`
	AssigneeID         *uuid.UUID      `json:"assignee_id"`
	ReporterID         *uuid.UUID      `json:"reporter_id"`
	DueDate            pgtype.Date     `json:"due_date"`
	Position           decimal.Decimal `json:"position"`
	Blocked            bool            `json:"blocked"`
	BlockedReason      *string         `json:"blocked_reason"`
	Source             string          `json:"source"`
	ExternalRef        *string         `json:"external_ref"`
	SourceMetadata     []byte          `json:"source_metadata"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.Number,
		arg.OrganizationID,
		arg.ProjectID,
		arg.Title,
		arg.Description,
		arg.AcceptanceCriteria,
		arg.Status,
		arg.Priority,
		arg.AssigneeID,
		arg.ReporterID,
		arg.DueDate,
		arg.Position,
		arg.Blocked,
		arg.BlockedReason,
		arg.Source,
		arg.ExternalRef,
		arg.SourceMetadata,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.OrganizationID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.AcceptanceCriteria,
		&i.Status,
		&i.Priority,
		&i.AssigneeID,
		&i.ReporterID,
		&i.DueDate,
		&i.Position,
		&i.Blocked,
		&i.BlockedReason,
		&i.Source,
		&i.ExternalRef,
		&i.SourceMetadata,
		&i.CompletionSummary,
		&i.Version,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTask = `-- name: GetTask :one
SELECT id, number, organization_id, project_id, title, description, acceptance_criteria, status, priority, assignee_id, reporter_id, due_date, position, blocked, blocked_reason, source, external_ref, source_metadata, completion_summary, version, archived_at, created_at, updated_at FROM tasks
WHERE id = $1
  AND archived_at IS NULL
`

func (q *Queries) GetTask(ctx context.Context, id uuid.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.OrganizationID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.AcceptanceCriteria,
		&i.Status,
		&i.Priority,
		&i.AssigneeID,
		&i.ReporterID,
		&i.DueDate,
		&i.Position,
		&i.Blocked,
		&i.BlockedReason,
		&i.Source,
		&i.ExternalRef,
		&i.SourceMetadata,
		&i.CompletionSummary,
		&i.Version,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskByExternalRef = `-- name: GetTaskByExternalRef :one
SELECT id, number, organization_id, project_id, title, description, acceptance_criteria, status, priority, assignee_id, reporter_id, due_date, position, blocked, blocked_reason, source, external_ref, source_metadata, completion_summary, version, archived_at, created_at, updated_at FROM tasks
WHERE project_id = $1
  AND external_ref = $2
  AND archived_at IS NULL
`

type GetTaskByExternalRefParams struct {
	ProjectID   uuid.UUID `json:"project_id"`
	ExternalRef *string   `json:"external_ref"`
}

func (q *Queries) GetTaskByExternalRef(ctx context.Context, arg GetTaskByExternalRefParams) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskByExternalRef, arg.ProjectID, arg.ExternalRef)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.OrganizationID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.AcceptanceCriteria,
		&i.Status,
		&i.Priority,
		&i.AssigneeID,
		&i.ReporterID,
		&i.DueDate,
		&i.Position,
		&i.Blocked,
		&i.BlockedReason,
		&i.Source,
		&i.ExternalRef,
		&i.SourceMetadata,
		&i.CompletionSummary,
		&i.Version,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskIncludingArchived = `-- name: GetTaskIncludingArchived :one
SELECT id, number, organization_id, project_id, title, description, acceptance_criteria, status, priority, assignee_id, reporter_id, due_date, position, blocked, blocked_reason, source, external_ref, source_metadata, completion_summary, version, archived_at, created_at, updated_at FROM tasks WHERE id = $1
`

func (q *Queries) GetTaskIncludingArchived(ctx context.Context, id uuid.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskIncludingArchived, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.OrganizationID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.AcceptanceCriteria,
		&i.Status,
		&i.Priority,
		&i.AssigneeID,
		&i.ReporterID,
		&i.DueDate,
		&i.Position,
		&i.Blocked,
		&i.BlockedReason,
		&i.Source,
		&i.ExternalRef,
		&i.SourceMetadata,
		&i.CompletionSummary,
		&i.Version,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTaskPositionsInColumn = `-- name: ListTaskPositionsInColumn :many
SELECT id, position
FROM tasks
WHERE project_id = $1
  AND status = $2
  AND archived_at IS NULL
ORDER BY position ASC
`

type ListTaskPositionsInColumnParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Status    string    `json:"status"`
}

type ListTaskPositionsInColumnRow struct {
	ID       uuid.UUID       `json:"id"`
	Position decimal.Decimal `json:"position"`
}

func (q *Queries) ListTaskPositionsInColumn(ctx context.Context, arg ListTaskPositionsInColumnParams) ([]ListTaskPositionsInColumnRow, error) {
	rows, err := q.db.Query(ctx, listTaskPositionsInColumn, arg.ProjectID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTaskPositionsInColumnRow{}
	for rows.Next() {
		var i ListTaskPositionsInColumnRow
		if err := rows.Scan(&i.ID, &i.Position); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasks = `-- name: ListTasks :many
SELECT t.id, t.number, t.organization_id, t.project_id, t.title, t.description, t.acceptance_criteria, t.status, t.priority, t.assignee_id, t.reporter_id, t.due_date, t.position, t.blocked, t.blocked_reason, t.source, t.external_ref, t.source_metadata, t.completion_summary, t.version, t.archived_at, t.created_at, t.updated_at
FROM tasks t
WHERE t.organization_id = $1
  AND t.archived_at IS NULL
  AND ($2::uuid IS NULL OR t.project_id = $2)
  AND ($3::uuid IS NULL OR t.assignee_id = $3)
  AND ($4::text IS NULL OR t.status = $4)
  AND ($5::text IS NULL OR t.priority = $5)
  AND ($6::boolean IS NULL OR t.blocked = $6)
  AND ($7::text IS NULL OR t.source = $7)
  AND ($8::timestamptz IS NULL OR t.updated_at >= $8)
  AND (
      $9::text IS NULL
      OR t.title ILIKE '%' || $9 || '%'
      OR t.description ILIKE '%' || $9 || '%'
      OR t.external_ref ILIKE '%' || $9 || '%'
  )
ORDER BY t.status, t.position ASC, t.created_at ASC
`

type ListTasksParams struct {
	OrganizationID uuid.UUID          `json:"organization_id"`
	ProjectID      *uuid.UUID         `json:"project_id"`
	AssigneeID     *uuid.UUID         `json:"assignee_id"`
	Status         *string            `json:"status"`
	Priority       *string            `json:"priority"`
	Blocked        *bool              `json:"blocked"`
	Source         *string            `json:"source"`
	UpdatedAfter   pgtype.Timestamptz `json:"updated_after"`
	Search         *string            `json:"search"`
}

func (q *Queries) ListTasks(ctx context.Context, arg ListTasksParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasks,
		arg.OrganizationID,
		arg.ProjectID,
		arg.AssigneeID,
		arg.Status,
		arg.Priority,
		arg.Blocked,
		arg.Source,
		arg.UpdatedAfter,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.OrganizationID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.AcceptanceCriteria,
			&i.Status,
			&i.Priority,
			&i.AssigneeID,
			&i.ReporterID,
			&i.DueDate,
			&i.Position,
			&i.Blocked,
			&i.BlockedReason,
			&i.Source,
			&i.ExternalRef,
			&i.SourceMetadata,
			&i.CompletionSummary,
			&i.Version,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxPositionInColumn = `-- name: MaxPositionInColumn :one
SELECT COALESCE(max(position), 0)::numeric AS max_position
FROM tasks
WHERE organization_id = $1
  AND ($2::uuid IS NULL OR project_id = $2)
  AND status = $3
  AND archived_at IS NULL
`

type MaxPositionInColumnParams struct {
	OrganizationID  uuid.UUID  `json:"organization_id"`
	FilterProjectID *uuid.UUID `json:"filter_project_id"`
	ColumnStatus    string     `json:"column_status"`
}

func (q *Queries) MaxPositionInColumn(ctx context.Context, arg MaxPositionInColumnParams) (decimal.Decimal, error) {
	row := q.db.QueryRow(ctx, maxPositionInColumn, arg.OrganizationID, arg.FilterProjectID, arg.ColumnStatus)
	var max_position decimal.Decimal
	err := row.Scan(&max_position)
	return max_position, err
}

const moveTask = `-- name: MoveTask :one
UPDATE tasks
SET
    status = $1,
    position = $2,
    version = version + 1,
    updated_at = now()
WHERE id = $3
  AND version = $4
  AND archived_at IS NULL
RETURNING id, number, organization_id, project_id, title, description, acceptance_criteria, status, priority, assignee_id, reporter_id, due_date, position, blocked, blocked_reason, source, external_ref, source_metadata, completion_summary, version, archived_at, created_at, updated_at
`

type MoveTaskParams struct {
	Status   string          `json:"status"`
	Position decimal.Decimal `json:"position"`
	ID       uuid.UUID       `json:"id"`
	Version  int32           `json:"version"`
}

func (q *Queries) MoveTask(ctx context.Context, arg MoveTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, moveTask,
		arg.Status,
		arg.Position,
		arg.ID,
		arg.Version,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.OrganizationID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.AcceptanceCriteria,
		&i.Status,
		&i.Priority,
		&i.AssigneeID,
		&i.ReporterID,
		&i.DueDate,
		&i.Position,
		&i.Blocked,
		&i.BlockedReason,
		&i.Source,
		&i.ExternalRef,
		&i.SourceMetadata,
		&i.CompletionSummary,
		&i.Version,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const normalizeTaskPositions = `-- name: NormalizeTaskPositions :exec
WITH ordered AS (
    SELECT id, (row_number() OVER (ORDER BY position, created_at) * 1000)::numeric AS new_pos
    FROM tasks
    WHERE tasks.project_id = $1
      AND tasks.status = $2
      AND tasks.archived_at IS NULL
)
UPDATE tasks t
SET position = ordered.new_pos, updated_at = now()
FROM ordered
WHERE t.id = ordered.id
`

type NormalizeTaskPositionsParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Status    string    `json:"status"`
}

func (q *Queries) NormalizeTaskPositions(ctx context.Context, arg NormalizeTaskPositionsParams) error {
	_, err := q.db.Exec(ctx, normalizeTaskPositions, arg.ProjectID, arg.Status)
	return err
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET
    title = COALESCE($1, title),
    description = COALESCE($2, description),
    acceptance_criteria = COALESCE($3, acceptance_criteria),
    status = COALESCE($4, status),
    priority = COALESCE($5, priority),
    assignee_id = COALESCE($6, assignee_id),
    due_date = COALESCE($7, due_date),
    position = COALESCE($8, position),
    blocked = COALESCE($9, blocked),
    blocked_reason = COALESCE($10, blocked_reason),
    source = COALESCE($11, source),
    external_ref = COALESCE($12, external_ref),
    source_metadata = COALESCE($13, source_metadata),
    completion_summary = COALESCE($14, completion_summary),
    version = version + 1,
    updated_at = now()
WHERE id = $15
  AND version = $16
  AND archived_at IS NULL
RETURNING id, number, organization_id, project_id, title, description, acceptance_criteria, status, priority, assignee_id, reporter_id, due_date, position, blocked, blocked_reason, source, external_ref, source_metadata, completion_summary, version, archived_at, created_at, updated_at
`

type UpdateTaskParams struct {
	Title              *string          `json:"title"`
	Description        *string          `json:"description"`
	AcceptanceCriteria *string          `json:"acceptance_criteria"`
	Status             *string          `json:"status"`
	Priority           *string          `json:"priority"`
	AssigneeID         *uuid.UUID       `json:"assignee_id"`
	DueDate            pgtype.Date      `json:"due_date"`
	Position           *decimal.Decimal `json:"position"`
	Blocked            *bool            `json:"blocked"`
	BlockedReason      *string          `json:"blocked_reason"`
	Source             *string          `json:"source"`
	ExternalRef        *string          `json:"external_ref"`
	SourceMetadata     []byte           `json:"source_metadata"`
	CompletionSummary  *string          `json:"completion_summary"`
	ID                 uuid.UUID        `json:"id"`
	ExpectedVersion    int32            `json:"expected_version"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.Title,
		arg.Description,
		arg.AcceptanceCriteria,
		arg.Status,
		arg.Priority,
		arg.AssigneeID,
		arg.DueDate,
		arg.Position,
		arg.Blocked,
		arg.BlockedReason,
		arg.Source,
		arg.ExternalRef,
		arg.SourceMetadata,
		arg.CompletionSummary,
		arg.ID,
		arg.ExpectedVersion,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.OrganizationID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.AcceptanceCriteria,
		&i.Status,
		&i.Priority,
		&i.AssigneeID,
		&i.ReporterID,
		&i.DueDate,
		&i.Position,
		&i.Blocked,
		&i.BlockedReason,
		&i.Source,
		&i.ExternalRef,
		&i.SourceMetadata,
		&i.CompletionSummary,
		&i.Version,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
